defaults: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV["POSTGRES_DB"] %>

test:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV["POSTGRES_TEST_DB"] %>

development:
  <<: *default

production:
  <<: *default
